# Generated by Django 3.1.5 on 2021-01-22 06:08

from django.db import migrations, models
import django.db.models.deletion
import treebeard_hierarchy.apps.tree.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterializedCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Materialized category',
                'verbose_name_plural': 'Materialized categories',
            },
            bases=(treebeard_hierarchy.apps.tree.models.HierarchyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NestedCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(db_index=True)),
                ('rgt', models.PositiveIntegerField(db_index=True)),
                ('tree_id', models.PositiveIntegerField(db_index=True)),
                ('depth', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Nested category',
                'verbose_name_plural': 'Nested categories',
            },
            bases=(treebeard_hierarchy.apps.tree.models.HierarchyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NesTedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nested_category_nested_product', to='tree.nestedcategory', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='MaterializedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_ideas', to='tree.materializedcategory', verbose_name='Category')),
            ],
        ),
    ]
